BMC_TO_PRIMER:
    D21-169 : 646 (CTGGACGC)
    D21-170 :  (TTGGCGCT)
    D21-171 :  (CGCTATGC)
    D21-172 :  (TCTTTATA)
    D21-173 :  (CGAGGTTA)
    D21-174 :  (GACTGGAT)
    D21-175 :  (GAGGGTCA)
    D21-176 :  (GTTTAGTC)
    D21-177 :  (CGACTTAT)
    D21-178 :  (AAAACTTG)
    D21-179 :  (CACGTAGG)
    D21-180 :  (ATTCTGCG)
    D21-181 :  (ATGTGAAA)
    D21-182 :  (GCGCACTG)
    D21-183 :  (GCCCCGCA)
    D21-184 :  (TAATGCCA)
    D21-185 :  (CACCGCTG)
    D21-186 :  (TGCGCTGT)
    D21-187 :  (CTAGCAGA)
    D21-188 :  (CGCGGCCC)
    D21-189 :  (GTAGATTG)
    D21-190 :  (CATCCTTT)
    D21-191 :  (CAAGTGTC)
    D21-192 :  (AAAAAGAC)
    D21-193 :  (GCATATAC)
    D21-194 :  (GCACGGGG)
    D21-195 :  (CCATCAAG)
    D21-196 :  (GATTAACA)
    D21-197 :  (CGCAGAAT)
    D21-198 :  (CGTGCATC)
    D21-199 :  (ACTCAAGA)
    D21-200 :  (CGTCACAC)
    D21-201 :  (AAGCTCAC)
    D21-202 :  (TTTCCCGA)
    D21-203 :  (CCTAGCGC)
    D21-204 :  (AGGACATT)
    D21-205 : 7a_600 (TAATAAGC)
    D21-206 : 7b_600 (AGCACTAC)
    D21-207 : 8a_600 (TGATACAG)
    D21-208 : 8b_600 (ATCGAAAG)
    D21-209 : E2a_600 (GAGTTTAG)
    D21-210 : E2b_600 (ATATAGGG)
    D21-211 : E3a_600 (GGGCGAGA)
    D21-212 : E3b_600 (GTTTGTCT)
    D21-213 : c1a_600 (CCTATGAA)
    D21-214 : c1b_600 (GGCAAACC)
    D21-215 : c2a_600 (CCGTGGCA)
    D21-216 : c2b_600 (TACTTTTT)

