# map the BioMicroCenter ID to my primer number and its corresponding illumina barcoding index
BMC_TO_PRIMER:
    D19-7910-1 : 178 (ATAGAGAG)
    D19-7911-1 : 179 (AGAGGATA)
    D19-7912-1 : 180 (CTCCTTAC)
    D19-7913-1 : 181 (TATGCAGT)
    D19-7914-1 : 182 (TACTCCTT)
    D19-7915-1 : 183 (AGGCTTAG)
    D19-7916-1 : 184 (ATTAGACG)
    D19-7917-1 : 185 (CGGAGAGA)
    D19-7918-1 : 186 (CTAGTCGA)
    D19-7919-1 : 187 (AGCTAGAA)
    D19-7920-1 : 188 (ACTCTAGG)
    D19-7921-1 : 189 (TCTTACGC)
    D19-7922-1 : 190 (CTTAATAG)
    D19-7923-1 : 191 (ATAGCCTT)
    D19-7924-1 : 192 (TAAGGCTC)
    D19-7925-1 : 193 (TCGCATAA)
    D19-7926-1 : 569 (CGCTATGT)
    D19-7927-1 : 570 (CAATTCAC)
    D19-7928-1 : 571 (GGAATGCA)
    D19-7929-1 : 572 (GAACGTGA)
    D19-7930-1 : 573 (GAAGTACT)
    D19-7931-1 : 574 (GGCCACCG)
    D19-7932-1 : 575 (CAGATGAG)
    D19-7933-1 : 576 (CTAAAGCT)
    D19-7934-1 : 577 (GTTTTGCG)
    D19-7935-1 : 578 (CCCGGCGC)
    D19-7936-1 : 579 (GGGAATTG)
    D19-7937-1 : 580 (TTCCAGGT)
    D19-7910-2 : 178 (ATAGAGAG)
    D19-7911-2 : 179 (AGAGGATA)
    D19-7912-2 : 180 (CTCCTTAC)
    D19-7913-2 : 181 (TATGCAGT)
    D19-7914-2 : 182 (TACTCCTT)
    D19-7915-2 : 183 (AGGCTTAG)
    D19-7916-2 : 184 (ATTAGACG)
    D19-7917-2 : 185 (CGGAGAGA)
    D19-7918-2 : 186 (CTAGTCGA)
    D19-7919-2 : 187 (AGCTAGAA)
    D19-7920-2 : 188 (ACTCTAGG)
    D19-7921-2 : 189 (TCTTACGC)
    D19-7922-2 : 190 (CTTAATAG)
    D19-7923-2 : 191 (ATAGCCTT)
    D19-7924-2 : 192 (TAAGGCTC)
    D19-7925-2 : 193 (TCGCATAA)
    D19-7926-2 : 569 (CGCTATGT)
    D19-7927-2 : 570 (CAATTCAC)
    D19-7928-2 : 571 (GGAATGCA)
    D19-7929-2 : 572 (GAACGTGA)
    D19-7930-2 : 573 (GAAGTACT)
    D19-7931-2 : 574 (GGCCACCG)
    D19-7932-2 : 575 (CAGATGAG)
    D19-7933-2 : 576 (CTAAAGCT)
    D19-7934-2 : 577 (GTTTTGCG)
    D19-7935-2 : 578 (CCCGGCGC)
    D19-7936-2 : 579 (GGGAATTG)
    D19-7937-2 : 580 (TTCCAGGT)

#to split a sample that contains toxin single mutants in the background of different antitoxin mutant backgrounds
#these indices are in the 5'->3' direction directly after the AAGCTT RE site
CELL_MIX_TO_AT_INDICES:
    1 :
        - TATC
        - CCAT
        - GAGT
        - CGTA
        - AGGG
        - ATTT
        - AAAA
        - GGAC
        - ACCC
        - TGCT
        - CACG
        - TTAG
        - CTGC
        - GCTG
        - TCGA
    2 :
        - TATC
        - CCAT
        - GAGT
        - CGTA
        - AGGG
        - ATTT
        - AAAA
        - GGAC
        - ACCC
        - TGCT
        - CACG
        - TTAG
        - CTGC
        - GCTG
        - TCGA
    3 :
        - TATC
        - CCAT
        - GAGT
        - CGTA
        - AGGG
        - ATTT
        - AAAA
        - GGAC
        - ACCC
        - TGCT
        - CACG
        - TTAG
        - CTGC
        - GCTG
        - TCGA
    4 :
        - TATC
        - CCAT
        - GAGT
        - CGTA
        - AGGG
        - ATTT
        - AAAA
        - GGAC
        - ACCC
        - TGCT
        - CACG
        - TTAG
        - CTGC
        - GCTG
        - TCGA
# dictionaries to map a 4 nucleotide barcode (on toxin vector after the 3' end and the restriction site) to an antitoxin background
AT_INDEX_TO_MUTKEY_1:
    TATC : G62A
    CCAT : wtAT
    GAGT : E61A
    CGTA : E61Q
    AGGG : E79R
    ATTT : K63L
    AAAA : R77L
    GGAC : R81A
    ACCC : G66D
    TGCT : K44R
    CACG : E61R
    TTAG : E79K
    CTGC : G66A
    GCTG : A80L
    TCGA : V17F

AT_INDEX_TO_MUTKEY_2:
    TATC : G62A
    CCAT : wtAT
    GAGT : E61A
    CGTA : E61Q
    AGGG : E79R
    ATTT : K63L
    AAAA : R77L
    GGAC : R81A
    ACCC : G66D
    TGCT : K44R
    CACG : E61R
    TTAG : E79K
    CTGC : G66A
    GCTG : A80L
    TCGA : V17F

AT_INDEX_TO_MUTKEY_3:
    CCAT : D60I
    GAGT : F73L
    ACCC : R81D
    CGTA : R77F
    AGGG : F73A
    GCTG : W59L
    TGCT : W59V
    TATC : W41L
    CTGC : G62D
    ATTT : V71F
    AAAA : I33V
    GGAC : A80K
    CACG : W59A
    TCGA : E26R
    TTAG : G62Y

AT_INDEX_TO_MUTKEY_4:
    CCAT : D60I
    GAGT : F73L
    ACCC : R81D
    CGTA : R77F
    AGGG : F73A
    GCTG : W59L
    TGCT : W59V
    TATC : W41L
    CTGC : G62D
    ATTT : V71F
    AAAA : I33V
    GGAC : A80K
    CACG : W59A
    TCGA : E26R
    TTAG : G62Y
